// Extend the retained Skeletal Lab flow; do not replace its original bank,
// styles, marker renderer, local progress key, or exact-spelling score.
(() => {
  const labels=D.exam1.topicLabels;
  const groups=[['Unit 2',['skull','axial','appendicular','landmarks','osteon']],['Exam 1',['regions','cavities','organs','systems','direction','planes']],['Histology',['adipose','reticular','blood','dense','hyaline','osteon','histology']],['Additional Exam 1',['microscope','cells']]];
  const presetNames={unit2:'Unit 2 Only',pictures:'Exam 1 Pictures',exam1:'Exam 1 Only',everything:'Everything / Cumulative',custom:'Custom Practice'};
  const ALL=Object.keys(labels),selectionKey='skullLabSelection';
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const defaults={preset:'unit2',topics:ALL,region:'all',view:'all',category:'all',count:'all',mode:'practice',missed:false};
  let selection={...defaults};try{const s=JSON.parse(localStorage.getItem(selectionKey)||'null');if(s&&Object.hasOwn(presetNames,s.preset))selection={...defaults,...s,topics:Array.isArray(s.topics)?s.topics.filter(t=>ALL.includes(t)):ALL};}catch{}
  const persist=()=>localStorage.setItem(selectionKey,JSON.stringify(selection));
  function eligible(){return Q.filter(q=>selection.preset==='unit2'?q.units.includes('unit2'):selection.preset==='exam1'?q.units.includes('exam1'):selection.preset==='pictures'?q.units.includes('exam1')&&q.visual:selection.preset==='custom'?q.topics.some(t=>selection.topics.includes(t)):true);}
  function filtered(){return eligible().filter(q=>(selection.region==='all'||q.region===selection.region)&&(selection.view==='all'||q.view===selection.view)&&(selection.category==='all'||q.category===selection.category));}
  function selectedMisses(){const p=load();return filtered().filter(q=>p.misses.includes(q.id));}
  // Shuffle within topics, then interleave topics. Every question appears at
  // most once; adjacent duplicate image+answer stations are avoided if possible.
  function varied(pool){const buckets=new Map();for(const q of shuffle([...new Map(pool.map(q=>[q.id,q])).values()])){const k=q.topics[0];if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(q);}const result=[];let lastTopic=null;while(buckets.size){let keys=[...buckets.keys()].filter(k=>k!==lastTopic);if(!keys.length)keys=[...buckets.keys()];const k=keys[Math.floor(Math.random()*keys.length)],bucket=buckets.get(k);let at=bucket.findIndex(q=>!result.length||q.image!==result.at(-1).image||norm(q.answer)!==norm(result.at(-1).answer));if(at<0)at=0;result.push(bucket.splice(at,1)[0]);if(!bucket.length)buckets.delete(k);lastTopic=k;}return result;}
  function makePool(mode=selection.mode){let pool=filtered();if(selection.missed){const p=load();pool=pool.filter(q=>p.misses.includes(q.id));}pool=varied(pool);const n=Number(selection.count);if(selection.count!=='all'&&Number.isInteger(n)&&n>0)pool=pool.slice(0,n);return pool;}
  function choosePreset(preset){selection={...selection,preset,region:'all',view:'all',category:'all',missed:false};persist();nav('home');}
  const originalNav=nav;
  nav=function(view,preserve=false){if(!preserve&&(view==='practice'||view==='exam')){const pool=makePool(view==='exam'?'exam':'practice');if(!pool.length){alert('No questions match your current selection. Choose topics in Study setup.');originalNav('home');return;}startSession(view==='exam'?'exam':'practice',pool);preserve=true;}originalNav(view,preserve);};
  const originalImage=imageMarkup;
  imageMarkup=function(q,alt='Course anatomy image with the target indicated'){if(q.unit!=='exam1')return originalImage(q,alt);if(!q.visual)return `<div class="written-station"><span class="eyebrow">Written review · No image station</span><p>${escape(q.prompt)}</p><span class="small">Answer the relationship, term, or course concept asked for.</span></div>`;if(q.hotspot)return originalImage(q,alt);return `<div class="image-frame"><div class="image-stage source-stage ${q.sourceIndicator?'micro-stage':''}"><img class="photo" src="${escape(q.image)}" alt="${escape(alt)}"></div><div class="hotspot-guide">${q.sourceIndicator?'Follow the single bold arrow in the original class image.':'Identify the phase shown in this instructional schematic.'}</div></div>`;};
  const originalEvidence=evidenceLabel;
  evidenceLabel=q=>q.unit==='exam1'?'Exam 1 source-supported study question':originalEvidence(q);
  const originalGrade=grade;
  grade=function(q,response){if(q.unit!=='exam1')return originalGrade(q,response);const given=norm(response).replace(/×/g,'x').replace(/[.!?]$/,''),accepted=[q.answer,...q.alternatives].map(x=>norm(x).replace(/×/g,'x')),exact=accepted.includes(given);if(exact)return{spelled:true,identified:true,kind:'correct'};
    // Never treat an opposite relationship or different studied tissue/organ
    // as a spelling error merely because its name is two characters away.
    const known=[...Q.filter(x=>x.unit==='exam1').flatMap(x=>[x.answer,...x.alternatives]),'nucleus','nucleolus','centrosome','centriole','centrioles','chondrocyte','osteocyte','osteoblast','osteoclast','mitosis','meiosis','medial','lateral','anterior','posterior','superior','inferior','proximal','distal','superficial','deep','simple','stratified','blood','bone'].map(norm);const required=q.requiredWords||[];
    const conflicts=known.includes(given)||required.some(w=>!given.includes(norm(w)))||(/\b(nonkeratinized|non keratinized)\b/.test(given)!==/\b(nonkeratinized|non keratinized)\b/.test(norm(q.answer))&&/keratinized/.test(given+q.answer));
    const near=given.length>3&&!conflicts&&Math.min(...accepted.map(a=>dist(given,a)))<=2;return{spelled:false,identified:near,kind:near?'spelling':'incorrect'};};
  const originalRecord=record;
  record=function(q,result,options={}){originalRecord(q,result,options);const p=load(),s=p.questions[q.id];s.lastResponse=options.response??(options.skipped?'Skipped':'');s.lastKind=result.kind||'incorrect';s.lastQuestion={prompt:q.prompt||'Identify the indicated anatomical structure.',image:q.image||null,hotspot:q.hotspot||window.HOTSPOTS.targets[q.id]||null};save(p);};
  function performance(rows){const buckets={};for(const row of rows){const q=row.q,k=q.unit==='exam1'?q.category:q.region,b=buckets[k]||(buckets[k]={correct:0,total:0});b.total+=row.attempts??1;b.correct+=row.spelled===true?1:Number(row.spelled)||0;}return Object.entries(buckets).map(([category,b])=>`<div class="statline"><span>${escape(category)}</span><b>${b.correct} / ${b.total}</b></div>`).join('')||'<p class="small">Submit answers to see performance by category.</p>';}
  function selectionPanel(){const qs=eligible();return `<section class="panel selection-panel"><h2>What do you want to practice?</h2><div class="preset-grid" role="group" aria-label="Practice scope">${Object.entries(presetNames).map(([key,name])=>`<button class="${selection.preset===key?'primary':'ghost'}" data-preset="${key}" aria-pressed="${selection.preset===key}">${name}</button>`).join('')}</div><p class="small">${escape(presetNames[selection.preset])} · ${qs.length} available questions${selection.preset==='pictures'?' · Images only, no written-only questions':''}. Your topic selection also applies to Learn, Identification, Exam simulation, and missed-question retries.</p>${selection.preset==='custom'?`<div class="actions"><button class="secondary" data-topics="all">Select everything</button><button class="ghost" data-topics="none">Clear all</button><button class="ghost" data-topics="unit2">Select Unit 2</button><button class="ghost" data-topics="exam1">Select Exam 1</button><button class="ghost" data-topics="histology">Histology only</button></div><div class="topic-grid">${groups.map(([group,topics])=>`<fieldset class="topic-group"><legend>${group}</legend>${topics.map(t=>`<label class="topic-check"><input type="checkbox" data-topic="${t}" ${selection.topics.includes(t)?'checked':''}> <span>${escape(labels[t])} <small>(${Q.filter(q=>q.topics.includes(t)).length})</small></span></label>`).join('')}</fieldset>`).join('')}</div><p class="small">Bone landmarks can overlap a skeletal region; Osteon belongs to both cumulative histology and Unit 2. A question matching several selections still appears only once.</p>`:''}<details><summary class="small">Professor’s cumulative topics and image coverage</summary><p class="note">Body regions, cavities, organs/systems, directional terms, and relevant histology return. Priority histology: adipose, reticular tissue, blood, dense regular connective tissue (tendons/ligaments), hyaline cartilage, and osteon.</p><p class="small">Adipose, dense regular tissue, and compact bone have class-image stations. Reticular tissue, blood, and hyaline cartilage currently have supported written review only; verified specimen images are still needed for visual recognition. Microscope and cell questions are optional Custom topics and included in Exam 1 Only / Everything.</p></details></section>`;}
  const originalHome=home;
  home=function(){const box=document.createElement('div');box.innerHTML=originalHome();box.querySelector('h1').textContent='Same images. More locations. Full practical review.';box.querySelector('.intro p').textContent='Keep practicing every original bone location, or add course-supported Exam 1 material for the cumulative practical.';box.querySelector('.countdown').textContent=Q.length+' study questions';const panel=box.querySelector('.grid>.panel');const note=panel.querySelector('.note');note.textContent='All 188 original Unit 2 questions remain intact, including the 12 professor-keyed stations. Exam 1 additions are source-supported study questions; the original professor’s practical has not been recreated or guaranteed.';const sourceList=box.querySelector('.source-list');sourceList.insertAdjacentHTML('beforeend','<li>Exam 1.zip · 17 usable files inspected</li><li>Exam 1 reference website / uploaded index.html</li>');box.querySelector('.intro').insertAdjacentHTML('afterend',selectionPanel());return box.innerHTML;};
  startFromControls=function(){captureControls();let pool=makePool();if(!pool.length){alert('No questions match those settings. Select at least one topic or broaden the filters.');return;}if(selection.count==='custom'){const n=Number(prompt(`How many questions? (1-${pool.length})`,String(Math.min(10,pool.length))));if(!Number.isInteger(n)||n<1)return;selection.count=String(Math.min(n,pool.length));persist();pool=pool.slice(0,+selection.count);}startSession(selection.mode,pool);nav(selection.mode==='exam'?'exam':'practice',true);};
  function captureControls(){for(const [id,key] of [['regionFilter','region'],['viewFilter','view'],['catFilter','category'],['countFilter','count'],['modeFilter','mode']]){const el=document.getElementById(id);if(el)selection[key]=el.value;}const missed=document.getElementById('missedOnly');if(missed)selection.missed=missed.checked;persist();}
  questionPanel=function(exam=false){const q=state.pool[state.index];if(!q)return exam?examResults():practiceComplete();const prompt=q.prompt||'What anatomical structure is indicated?';return `<div class="intro"><div><div class="eyebrow">${exam?'Exam simulation':'Identification practice'} · ${q.unit==='exam1'?'Exam 1 cumulative':escape(q.region)}</div><h1>${exam?`Question ${state.index+1} of ${state.pool.length}`:q.unit==='exam1'?'Practical identification':state.mode==='spelling'?'Spell the structure':'What anatomical structure is indicated?'}</h1><p>${escape(prompt)}</p></div>${exam?'<span class="small">No hints or feedback during this set</span>':'<button class="ghost" id="skip">Skip for now</button>'}</div><div class="progressbar"><i style="width:${state.index/state.pool.length*100}%"></i></div><div class="question-layout"><section class="panel">${imageMarkup(q)}<div class="meta" style="margin-top:10px">${escape(q.source)} · ${evidenceLabel(q)}</div></section><aside class="panel"><span class="pill">${escape(q.view)}</span><h2>${exam?'Station prompt':'Your answer'}</h2><form id="answerForm"><label class="small" for="answer">${q.visual?'Requested anatomical term':'Requested answer'}</label><div class="answer-row"><input id="answer" autocomplete="off" autocapitalize="off" autofocus required><button class="primary">${exam?'Next':'Check answer'}</button></div></form><div id="feedback"></div>${!exam&&q.unit!=='exam1'?`<div class="note">${escape(q.category)} · ${escape(q.bone)}</div>`:''}</aside></div>`;};
  afterPractice=function(){const q=state.pool[state.index],form=document.getElementById('answerForm');form.onsubmit=e=>{e.preventDefault();if(state.answered)return;const response=document.getElementById('answer').value,result=grade(q,response);state.answered=true;record(q,result,{response});state.examAnswers.push({q,response,...result});const f=document.getElementById('feedback');f.className='feedback '+result.kind;f.innerHTML=`<strong>${result.spelled?'Correct.':result.identified?'Correct concept; spelling needs work.':'Identification / content error.'}</strong> Correct answer: <b>${escape(q.answer)}</b><br>${escape(q.tip)}`;form.querySelector('button').outerHTML='<button type="button" class="primary" id="next">Next question</button>';document.getElementById('answer').disabled=true;document.getElementById('next').onclick=()=>{state.index++;state.answered=false;render();};};document.getElementById('skip').onclick=()=>{record(q,{identified:false,spelled:false,kind:'incorrect'},{skipped:true,response:'Skipped'});state.examAnswers.push({q,response:'Skipped',identified:false,spelled:false,kind:'incorrect'});state.index++;state.answered=false;render();};};
  afterExam=function(){const q=state.pool[state.index];document.getElementById('answerForm').onsubmit=e=>{e.preventDefault();if(state.answered)return;state.answered=true;const response=document.getElementById('answer').value,result=grade(q,response);state.examAnswers.push({q,response,...result});record(q,result,{response});state.index++;state.answered=false;render();};};
  const originalComplete=practiceComplete;
  practiceComplete=function(){const misses=selectedMisses();return `<section class="panel empty"><div class="eyebrow">Set complete · ${escape(presetNames[selection.preset])}</div><h1>Practice set finished</h1><p>${misses.length} question${misses.length===1?'':'s'} in this selection need review.</p><div class="actions" style="justify-content:center">${misses.length?'<button class="primary" id="practiceMisses">Practice missed questions</button>':''}<button class="ghost" id="newSet">Choose another set</button></div></section><section class="panel" style="margin-top:22px"><h2>Performance by category · this set</h2>${performance(state.examAnswers)}</section>`;};
  function reviewCard(q,response,kind){return `<article class="review-card">${imageMarkup(q,'Original course image and target from the missed question')}<span class="pill">${escape(q.unit==='exam1'?q.category:q.region)}</span><p class="small">${escape(q.prompt||'Identify the indicated anatomical structure.')}</p><h3>Correct answer: ${escape(q.answer)}</h3><p class="small">Your answer: ${escape(response||'Not recorded in an older attempt')}<br>${kind==='spelling'?'Identification correct; spelling needs review':'Identification / content needs review'}</p><p class="note">${escape(q.tip)}</p></article>`;}
  const originalResults=examResults;
  examResults=function(){const box=document.createElement('div');box.innerHTML=originalResults();const reviews=box.querySelector('.review-grid');if(reviews)reviews.innerHTML=state.examAnswers.filter(x=>!x.spelled).map(x=>reviewCard(x.q,x.response,x.kind)).join('');box.querySelector('.panel').insertAdjacentHTML('beforeend',`<h2 style="margin-top:20px">Performance by category</h2>${performance(state.examAnswers)}`);return box.innerHTML;};
  const originalLearn=learn;
  learn=function(){const qs=filtered();if(!qs.length)return '<section class="panel empty"><h1>No topics selected</h1><p>Choose topics in Study setup before opening Learn.</p><button class="ghost" id="learnSetup">Choose topics</button><button id="toggleLabels" hidden>Reveal details</button></section>';if(!qs.some(q=>q.id===state.learn?.id))state.learn=qs[0];const q=state.learn;return `<section class="intro"><div><div class="eyebrow">Learn mode · ${escape(presetNames[selection.preset])}</div><h1>Review one marked structure at a time</h1><p>Only your selected topics are shown. Written-only review is clearly identified.</p></div><button class="ghost" id="toggleLabels">${state.hideInfo?'Reveal details':'Hide details'}</button></section><div class="question-layout"><section class="panel">${imageMarkup(q)}<p class="small">${escape(q.prompt||'Identify the indicated structure.')}</p><p class="meta">${escape(q.source)}</p></section><aside class="panel"><span class="pill">${escape(q.view)}</span><h2>${state.hideInfo?'Details hidden':escape(q.answer)}</h2>${state.hideInfo?'<p class="small">Reveal details when ready to check yourself.</p>':`<div class="statline"><span>${q.unit==='exam1'?'Topic':'Associated bone'}</span><b>${escape(q.unit==='exam1'?q.category:q.bone)}</b></div><div class="statline"><span>Evidence level</span><b>${evidenceLabel(q)}</b></div><div class="note">${escape(q.tip)}</div>`}</aside></div><section class="panel" style="margin-top:22px"><h2>${qs.length} selected study questions</h2><div class="learn-list">${qs.map(x=>`<button class="learn-card ${x.id===q.id?'active':''}" data-learn="${x.id}"><span class="pill">${escape(state.hideInfo&&x.unit==='exam1'?'Exam 1':x.unit==='exam1'?x.category:x.region)}</span><br><b>${state.hideInfo?'Details hidden':escape(x.answer)}</b><br><span class="small">${escape(x.view)}</span></button>`).join('')}</div></section>`;};
  const originalProgress=progress;
  progress=function(){const box=document.createElement('div');box.innerHTML=originalProgress();const p=load(),misses=Q.filter(q=>p.misses.includes(q.id));box.querySelector('.grid').insertAdjacentHTML('afterend',`<section class="panel" style="margin-top:22px"><h2>Performance by category · all saved attempts</h2>${performance(Q.filter(q=>p.questions[q.id]).map(q=>({q,...p.questions[q.id]})))}</section><section class="panel" style="margin-top:22px"><h2>Missed-question review</h2><p class="small">The review shows all saved misses. Retry uses only the topics currently selected in Study setup.</p>${selectedMisses().length?'<button class="primary" id="retrySelected">Practice selected missed questions</button>':''}<div class="review-grid" style="margin-top:16px">${misses.map(q=>reviewCard(q,p.questions[q.id]?.lastResponse,p.questions[q.id]?.lastKind)).join('')}</div></section>`);return box.innerHTML;};
  const originalCoverage=coverage;
  coverage=function(){let html=originalCoverage();const perTopic=Object.keys(labels).filter(t=>!['skull','axial','appendicular','landmarks'].includes(t)).map(t=>{const qs=Q.filter(q=>q.units.includes('exam1')&&q.topics.includes(t)),visual=qs.filter(q=>q.visual).length;return `<tr><td>${escape(labels[t])}</td><td>${qs.length} questions</td><td><span class="status ${visual?'playable':'needed'}">${visual?visual+' visual stations':'Written review only'}</span></td></tr>`;}).join('');return html+`<section class="panel" style="margin-top:22px"><h2>Exam 1 cumulative coverage</h2><p class="small">All ${D.exam1.scope.inspectedFiles} usable ZIP files were inspected (${D.exam1.scope.pdfPages} PDF pages and 3 photographs), along with both websites. This bank samples supported course concepts; question counts do not mean every term is visually covered.</p><div class="table-scroll"><table class="coverage"><thead><tr><th>Topic</th><th>Study questions</th><th>Image coverage</th></tr></thead><tbody>${perTopic}</tbody></table></div><p class="note">Reticular tissue, blood, and hyaline cartilage need verified specimen images for visual recognition. They are included in written review, not falsely labeled as playable image locations.</p><h3>Source conflicts kept out of scored visual practice</h3><ul class="source-list">${D.exam1.scope.excluded.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><p class="small">${escape(D.exam1.scope.attribution)} <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/1-introduction" target="_blank" rel="noopener">OpenStax textbook</a> · <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">License</a></p></section>`;};
  const originalRender=render;
  render=function(){originalRender();if(state.view==='home'){
    document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{captureControls();choosePreset(b.dataset.preset);});
    document.querySelectorAll('[data-topic]').forEach(c=>c.onchange=()=>{captureControls();if(c.checked)selection.topics=[...new Set([...selection.topics,c.dataset.topic])];else selection.topics=selection.topics.filter(t=>t!==c.dataset.topic);persist();render();});
    document.querySelectorAll('[data-topics]').forEach(b=>b.onclick=()=>{captureControls();const k=b.dataset.topics;selection.topics=k==='all'?ALL:k==='none'?[]:k==='unit2'?groups[0][1]:k==='histology'?groups[2][1]:[...new Set([...groups[1][1],...groups[2][1],...groups[3][1]])];selection.region=selection.view=selection.category='all';persist();render();});
    const qs=eligible();for(const [id,key,field,title] of [['regionFilter','region','region','All selected regions'],['viewFilter','view','view','All selected images and views'],['catFilter','category','category','All selected categories']]){const el=document.getElementById(id),opts=[...new Set(qs.map(q=>q[field]))];el.innerHTML=`<option value="all">${title}</option>`+opts.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join('');if(selection[key]!=='all'&&!opts.includes(selection[key]))selection[key]='all';el.value=selection[key];el.onchange=captureControls;}
    const count=document.getElementById('countFilter');if(![...count.options].some(x=>x.value===selection.count))count.add(new Option(selection.count+' questions',selection.count));count.value=selection.count;count.onchange=captureControls;document.getElementById('modeFilter').value=selection.mode;document.getElementById('modeFilter').onchange=captureControls;document.getElementById('missedOnly').checked=selection.missed;document.getElementById('missedOnly').onchange=captureControls;
    document.getElementById('openLearn').onclick=()=>{captureControls();nav('learn');};document.getElementById('startSet').disabled=!filtered().length;
  }
    const retry=document.getElementById('practiceMisses')||document.getElementById('retrySelected');if(retry)retry.onclick=()=>{startSession('practice',varied(selectedMisses()));nav('practice',true);};
    const again=document.getElementById('examAgain');if(again)again.onclick=()=>{const pool=makePool('exam');if(pool.length){startSession('exam',pool);render();}};
    const setup=document.getElementById('learnSetup');if(setup)setup.onclick=()=>nav('home');
  };
  window.CUMULATIVE={eligible,filtered,makePool,varied,selection:()=>JSON.parse(JSON.stringify(selection)),choosePreset,selectTopics:topics=>{selection={...selection,preset:'custom',topics,region:'all',view:'all',category:'all'};persist();},grade,escape};
  render();
})();
