// Professor-verified skull question bank. Add future anatomy modules as new arrays.
window.STUDY_DATA = {
  module: "skull",
  sources: {
    termSheet: "Practical 2_238_Term Sheet.pdf, pp. 1-2",
    practical: "Virtual+Practical+2_nosin.pptx, slides 8-11; answer key slide 27",
    photos: "Bone images for practical.pdf, pp. 4-7"
  },
  questions: [
    {id:"sk-09", answer:"Supraorbital notch", alternatives:["supraorbital foramen"], category:"Foramen & notch", view:"Anterior", bone:"Frontal bone", image:"assets/skull-anterior-source.jpg", marker:{x:30,y:30}, source:"PowerPoint slide 8, question 9; key slide 27", verification:"verified", tip:"Find the small opening/notch on the superior orbital margin."},
    {id:"sk-10", answer:"Inferior orbital fissure", alternatives:[], category:"Fissure", view:"Anterior", bone:"Sphenoid bone", image:"assets/skull-anterior-source.jpg", marker:{x:30,y:45}, source:"PowerPoint slide 8, question 10; key slide 27", verification:"verified", tip:"This is the long cleft at the posterior-inferior part of the orbit."},
    {id:"sk-11", answer:"Mental protuberance", alternatives:[], category:"Process & landmark", view:"Anterior", bone:"Mandible", image:"assets/skull-anterior-source.jpg", marker:{x:50,y:91}, source:"PowerPoint slide 8, question 11; key slide 27", verification:"verified", tip:"The mental protuberance is the midline prominence of the chin."},
    {id:"sk-12", answer:"Crista galli", alternatives:[], category:"Process & landmark", view:"Internal cranial cavity", bone:"Ethmoid bone", image:"assets/skull-internal-source.jpg", marker:{x:50,y:23}, source:"PowerPoint slide 9, question 12; key slide 27", verification:"verified", tip:"Look for the narrow midline ridge in the anterior cranial fossa."},
    {id:"sk-13", answer:"Sella turcica", alternatives:[], category:"Fossa", view:"Internal cranial cavity", bone:"Sphenoid bone", image:"assets/skull-internal-source.jpg", marker:{x:50,y:43}, source:"PowerPoint slide 9, question 13; key slide 27", verification:"verified", tip:"The sella turcica is the saddle-like depression centered in the sphenoid."},
    {id:"sk-14", answer:"Jugular foramen", alternatives:[], category:"Foramen & notch", view:"Internal cranial cavity", bone:"Temporal/occipital bones", image:"assets/skull-internal-source.jpg", marker:{x:65,y:55}, source:"PowerPoint slide 9, question 14; key slide 27", verification:"verified", tip:"This large irregular opening sits lateral to the foramen magnum."},
    {id:"sk-15", answer:"Palatine bone", alternatives:[], category:"Facial bone", view:"Inferior", bone:"Palatine bone", image:"assets/skull-inferior-source.jpg", marker:{x:50,y:27}, source:"PowerPoint slide 10, question 15; key slide 27", verification:"verified", tip:"On the inferior skull, it forms the posterior portion of the hard palate."},
    {id:"sk-16", answer:"Foramen ovale", alternatives:[], category:"Foramen & notch", view:"Inferior", bone:"Sphenoid bone", image:"assets/skull-inferior-source.jpg", marker:{x:34,y:43}, source:"PowerPoint slide 10, question 16; key slide 27", verification:"verified", tip:"The foramen ovale is the larger oval opening in the greater wing of the sphenoid."},
    {id:"sk-17", answer:"Styloid process", alternatives:[], category:"Process & landmark", view:"Inferior", bone:"Temporal bone", image:"assets/skull-inferior-source.jpg", marker:{x:28,y:58}, source:"PowerPoint slide 10, question 17; key slide 27", verification:"verified", tip:"The styloid process is the thin, pointed projection beside the temporal bone."},
    {id:"sk-18", answer:"Condylar process", alternatives:[], category:"Process & landmark", view:"Lateral", bone:"Mandible", image:"assets/mandible-lateral-source.jpg", marker:{x:46,y:24}, source:"PowerPoint slide 11, question 18; key slide 27", verification:"verified", tip:"At the posterior end of the mandibular ramus, the condylar process is the rounded articular projection."},
    {id:"sk-19", answer:"Sagittal suture", alternatives:[], category:"Suture", view:"Superior", bone:"Parietal bones", image:"assets/skull-superior-source.jpg", marker:{x:54,y:23}, source:"PowerPoint slide 11, question 19; key slide 27", verification:"verified", tip:"This midline suture runs anteroposteriorly between the two parietal bones."},
    {id:"sk-20", answer:"Lambdoid suture", alternatives:[], category:"Suture", view:"Superior", bone:"Parietal/occipital bones", image:"assets/skull-superior-source.jpg", marker:{x:55,y:69}, source:"PowerPoint slide 11, question 20; key slide 27", verification:"verified", tip:"The lambdoid suture crosses the posterior skull between the parietals and occipital bone."}
  ],
  coverage: [
    ["Frontal bone", "required", "No verified marked question yet"], ["Frontal sinus", "required", "No verified marked question yet"], ["Supraorbital foramen (notch)", "playable", "Q9 (key uses 'Supraorbital notch')"], ["Superciliary arch", "required", "No verified marked question yet"], ["Coronal suture", "required", "No verified marked question yet"], ["Supraorbital margin", "required", "No verified marked question yet"],
    ["Parietal bones", "required", "No verified marked question yet"], ["Sagittal suture", "playable", "Q19"],
    ["Temporal bones", "required", "No verified marked question yet"], ["Squamous suture", "required", "No verified marked question yet"], ["Carotid canal", "required", "No verified marked question yet"], ["External acoustic (auditory) meatus", "required", "No verified marked question yet"], ["Internal acoustic (auditory) meatus", "required", "No verified marked question yet"], ["Mandibular fossa", "required", "No verified marked question yet"], ["Mastoid process", "required", "No verified marked question yet"], ["Styloid process", "playable", "Q17"], ["Jugular foramen", "playable", "Q14"], ["Petrous portion", "required", "No verified marked question yet"],
    ["Occipital bone", "required", "No verified marked question yet"], ["External occipital protuberance", "required", "No verified marked question yet"], ["Foramen magnum", "required", "No verified marked question yet"], ["Lambdoid suture", "playable", "Q20"], ["Occipital condyle", "required", "No verified marked question yet"],
    ["Sphenoid bone", "required", "No verified marked question yet"], ["Foramen ovale", "playable", "Q16"], ["Foramen rotundum", "required", "No verified marked question yet"], ["Foramen spinosum", "required", "No verified marked question yet"], ["Foramen lacerum", "required", "No verified marked question yet"], ["Greater wing of sphenoid", "required", "No verified marked question yet"], ["Lesser wing of sphenoid", "required", "No verified marked question yet"], ["Inferior orbital fissure", "playable", "Q10"], ["Superior orbital fissure", "required", "No verified marked question yet"], ["Optic foramen", "required", "No verified marked question yet"], ["Sella turcica", "playable", "Q13"], ["Sphenoidal sinus", "required", "No verified marked question yet"],
    ["Ethmoid bone", "required", "No verified marked question yet"], ["Cribriform plate", "required", "No verified marked question yet"], ["Crista galli", "playable", "Q12"], ["Middle nasal concha", "required", "No verified marked question yet"], ["Ethmoid sinus", "required", "No verified marked question yet"],
    ["Mandible", "required", "No verified marked question yet"], ["Condylar process", "playable", "Q18"], ["Coronoid process", "required", "No verified marked question yet"], ["Mental foramen", "required", "No verified marked question yet"], ["Mental protuberance", "playable", "Q11"], ["Maxilla", "required", "No verified marked question yet"], ["Infraorbital foramen", "required", "No verified marked question yet"], ["Maxillary sinus", "required", "No verified marked question yet"], ["Palatine bone", "playable", "Q15"], ["Zygomatic bone", "required", "No verified marked question yet"], ["Lacrimal bones", "required", "No verified marked question yet"], ["Nasal bones", "required", "No verified marked question yet"], ["Vomer", "required", "No verified marked question yet"], ["Inferior nasal concha bones", "required", "No verified marked question yet"], ["Hyoid bone", "required", "No verified marked question yet"],
    ["Sphenoidal fontanel", "required", "No verified marked question yet"], ["Mastoid fontanel", "required", "No verified marked question yet"], ["Anterior fontanel", "required", "No verified marked question yet"], ["Posterior fontanel", "required", "No verified marked question yet"]
  ]
};
